assert myFunction.sum_array([1,2,3,4,5]) == [15], 'incorrect'
assert myFunction.sum_array([2,4,6]) == [12], 'incorrect'
assert myFunction.sum_array(3,-1,0) == [2], 'incorrect'
assert myFunction.fibonacci(1) == [1], 'incorrect'
assert myFunction.fibonacci(2) == [1], 'incorrect'
assert myFunction.fibonacci(3) == [2], 'incorrect'
assert myFunction.factorial(1) == [1], 'incorrect'
assert myFunction.factorial(2) == [2], 'incorrect'
assert myFunction.factorial(3) == [6], 'incorrect'
assert myFunction.reverse('top') == ['pot'], 'incorrect'
assert myFunction.reverse('honey') == ['yenoh'], 'incorrect'
assert myFunction.reverse('lamppost') == ['tsoppmal'], 'incorrect'
assert myFunction.reverse('Madam I am Adam') == ['madA ma I madaM'], 'incorrect'
